;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "John Doe"
      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "JetBrains Mono" :size 13.0 :dpi 96 :weight 'regular)
      doom-variable-pitch-font (font-spec :family "CMU Serif" :size 13.0 :dpi 96))

;; PROPER FIX: Work with Doom's font system instead of fighting it
;; The issue: Doom's font system in doom-ui.el overrides manual fontset configurations
;; Solution: Use Doom's variables and hook into their system properly

;; Step 1: Configure Doom's font variables to prevent emoji font usage
(setq use-default-font-for-symbols nil
      inhibit-compacting-font-caches t)

;; Step 2: Set doom-symbol-font to prioritize monospace font for symbols
(setq doom-symbol-font (font-spec :family "JetBrains Mono"
                                  :size 13
                                  :registry "iso10646-1"))

;; Step 3: Disable emoji font entirely by setting it to nil AND clearing fallbacks
;; This prevents Doom from setting up emoji fonts in the first place
(setq doom-emoji-font nil
      ;; CRITICAL: Also clear the fallback list so Doom can't find Apple Color Emoji
      doom-emoji-fallback-font-families nil)

;; Step 4: Define function to fix problematic symbols after Doom's font setup
(defun +doom-fix-symbol-fonts-h ()
  "Fix unicode symbol rendering by forcing specific symbols to use monospace font.
This runs AFTER Doom's font setup to override emoji fallbacks."
  (when (display-graphic-p)
    ;; CRITICAL: Include registry to ensure proper font resolution
    (let ((mono-font (font-spec :family "JetBrains Mono"
                               :size 13
                               :registry "iso10646-1")))
      ;; Override specific problematic characters that often render as emoji
      (dolist (char '(?⏺ ?✳ ?▶ ?◀ ?■ ?□ ?● ?○ ?★ ?☆ ?◆ ?◇ ?▪ ?▫ ?⚠ ?⚙ ?→ ?← ?↑ ?↓))
        (set-fontset-font t char mono-font nil 'prepend))

      ;; Override key Unicode ranges to prevent emoji fallback
      (dolist (range '((#x25A0 . #x25FF)  ; Geometric Shapes
                       (#x2600 . #x26FF)  ; Miscellaneous Symbols (includes ⚠ ⚙)
                       (#x2190 . #x21FF)  ; Arrows
                       (#x2500 . #x257F))) ; Box Drawing
        (set-fontset-font t range mono-font nil 'prepend))

      (message "Fixed unicode symbol fonts to use monospace"))))

;; Step 5: Hook into Doom's font system properly
;; This ensures our fixes run AFTER Doom sets up its emoji/symbol fonts
(add-hook 'after-setting-font-hook #'+doom-fix-symbol-fonts-h)

;; Step 5.5: Additional safeguard - override Doom's emoji font initialization
;; This advice runs before Doom's font initialization to ensure clean state
(defadvice! +doom-prevent-emoji-fonts-a (&rest _)
  "Prevent Doom from setting up emoji fonts by clearing fallback families."
  :before #'doom-init-fonts-h
  (setq doom-emoji-font nil
        doom-emoji-fallback-font-families nil))

;; Step 6: Also run after doom themes load (themes can affect fonts)
(after! doom-themes
  (+doom-fix-symbol-fonts-h))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'catppuccin)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `add-hook!' for adding functions to hooks
;; - `quiet!' for suppressing output generated by a call to a function
;; - `pushnew!' for adding a new element to a list, avoiding duplicates
;; - `delq!' for deleting elements from lists
;; - `delete!' for deleting files or directories
;; - `define-key!' for binding keys
;; - `undefine-key!' for unbinding keys

;;; ================================================================
;;;                UNIFIED EUPORIE INTEGRATION ARCHITECTURE
;;; ================================================================

;; Load euporie termint integration
(let ((doom-dir (or (bound-and-true-p doom-user-dir)
                   (expand-file-name "~/.doom.d/"))))
  (load (expand-file-name "euporie-termint.el" doom-dir)))

;; Global termint configuration
(setq termint-backend 'eat)

;; Hook into org-mode for unified euporie integration
(add-hook 'org-mode-hook 
  (lambda ()
    ;; Essential org-babel configuration
    (setq org-src-fontify-natively t
          org-src-preserve-indentation t 
          org-src-tab-acts-natively t)
    
    ;; Org-babel language support (now handled by euporie-unified.el)
    (setq org-babel-load-languages '((emacs-lisp . t)
                                     (python . t)
                                     (R . t)
                                     (stata . t)
                                     (sas . t)))
    
    ;; Essential org-src window setup
    (setq org-src-window-setup 'current-window
          org-support-shift-select 'always)))

;; Doom-specific configuration that needs to run after doom loads
(after! org
  ;; CRITICAL: Popup rules for org-src buffers - required for org-edit-src-code
  (set-popup-rule! "^\\*Org Src" :ignore t)
  (set-popup-rule! "^\\*SAS Console" :ignore t)

  ;; Note: Keybindings moved to hooks at end of file for proper override
  )

;; Claude Code IDE configuration (moved to separate file for better organization)
(load! "claude-code-config")


;; Load SAS org-babel integration
(load! "ob-sas")

;;; ================================================================
;;;                          KEYBINDINGS
;;; ================================================================

;; Set up Shift-Enter keybinding for euporie in org-src buffers (avoiding Doom C-RET conflicts)
(add-hook 'org-src-mode-hook
  (lambda ()
    (local-set-key (kbd "S-RET") #'euporie-send-region-or-paragraph)
    (local-set-key (kbd "S-<return>") #'euporie-send-region-or-paragraph)))

;; Also add to major mode hooks as backup
(defun euporie-setup-keybindings ()
  "Set up Shift-Enter keybindings for euporie in source code buffers."
  ;; Set keybindings in any org-src buffer or when babel-info is available
  (when (or (and (boundp 'org-src--babel-info) org-src--babel-info)
            (string-match-p "\\*Org Src" (buffer-name)))
    (local-set-key (kbd "S-RET") #'euporie-send-region-or-paragraph)
    (local-set-key (kbd "S-<return>") #'euporie-send-region-or-paragraph)))

(add-hook 'python-mode-hook #'euporie-setup-keybindings)
(add-hook 'ess-r-mode-hook #'euporie-setup-keybindings)
(add-hook 'SAS-mode-hook #'euporie-setup-keybindings)
(add-hook 'stata-mode-hook #'euporie-setup-keybindings)

